name: Fetch VPN Configs

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the script to fetch configs
        run: python get_configs.py

      - name: Commit and push if changes are detected
        run: |
          git config --local user.name "arshiacomplus"
          git config --local user.email "163334604+arshiacomplus@users.noreply.github.com"

          git add configs.txt

          # بررسی تغییرات و کامیت
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: Auto-update configs"
            git push
          fi
